= 001 - Maven Project Generation

* Status: proposed
* Decision makers: Support and Care Dev Team
* Date: 2025-10-02
* Related issues: https://github.com/support-and-care/maven-initializer/issues/14[GitHub #14], https://github.com/support-and-care/maven-initializer/issues/6[GitHub #6]


=== Context and Problem Description
The Maven Initializer should help to generate a ready-to-use Maven project structure.
The core of the application is to generate the necessary project files.
In the past, others already solved this problem.
Therefore, there is a chance to reuse their solution.


=== Considered Options

* Reuse Maven Archetype Components
* Mavenizerve Toolbox
* Custom solution based on a template engine

=== Decision

Chosen option: """, because [justification. e.g., only option, which meets k.o. criterion decision driver | which resolves force force | … | comes out best (see below)].

==== Positive Consequences

* [e.g., improvement of quality attribute satisfaction, follow-up decisions required, …]
* …

==== Negative Consequences

* [e.g., compromising quality attribute, follow-up decisions required, …]
* …

=== Pros and Cons of the Options

==== Reuse Maven Archetype Components

Apache Maven has an own mechansim for new project generation that realize as a Maven Plugin.
This plugin has common components that are responseable for the generation part.
The integration of the common components is tricky, because they depend on Maven Core infrastructure.
Nevertheless, we have to add some custom implementation for matching our requirements (for example, add dependencies)

* *Good*: Many ready-to-use templates exist.
* *Good*: Generator implementation exists.
* *Bad*: Custom adjustment for matching our requirements is high.
* *Bad*: Dependency Hell
* *Bad*: Integration to other components is not so easy (field-injection)

==== Mavenizerve Toolbox

Started as show case for [MIMA Resolver], but has a ready-to-use Java DSL for POM generation.
This Java DSL is demonstrated in own Maven plugin / CLI tool, but it can be used as library.

* *Good*: DSL-based
* *Good*: Good integration
* *Good*: Good abstraction of the Maven infrastructure

==== Custom solution based on a template engine

New CLI

* *Good*: We would have the full control.
* *Bad*: We have to implement everything from scratch
* *Bad*: Increase maintenance



=== Links
- https://github.com/sparsick/embedded-maven-shared-toolbox[PoC with shared Mavenizerve Toolbox]
- https://github.com/sparsick/embedded-maven-archetype[PoC with Maven Archetype]