= 001 - Maven Project Generation

* Status: accepted
* Decision makers: Support and Care Dev Team
* Date: 2025-10-07
* Related issues: https://github.com/support-and-care/maven-initializer/issues/14[GitHub #14], https://github.com/support-and-care/maven-initializer/issues/6[GitHub #6]


=== Context and Problem Description
The Maven Initializer should help to generate a ready-to-use Maven project structure.
The core of the application is to generate the necessary project files.
In the past, others already solved this problem.
Therefore, there is a chance to reuse their solution.
We want to take a look at an existing solution and compare them with a custom solution based on a template engine.


=== Considered Options

* Reuse Maven Archetype Components
* Mavenizerve Toolbox
* Custom solution based on a template engine

=== Decision

*Mavenizerve Toolbox*

We like the Java-DSL approach, making it straightforward to use programmatically.
It has already methods like `addDependencies` that can help to realize our requirements very easily.
It also is implemented by Maven maintainer, and it is an active project.

==== Positive Consequences

* Toolbox is a library coming from the Maven community.
* Java DSL approach simplifies the programmatical way of configuration.
* It is actively maintained.


=== Pros and Cons of the Options

==== Reuse Maven Archetype Components

Apache Maven has its own mechanism for generating new projects, which is realized as a Maven Plugin.
This plugin has common components that are responsible for the generation part.
The integration of the common components is tricky because they depend on Maven Core infrastructure.
Nevertheless, we have to add some custom implementation for matching our requirements, (for example, add dependencies)

* *Good*: Many ready-to-use templates exist.
* *Good*: Generator implementation exists.
* *Bad*: Custom adjustment for matching our requirements is high.
* *Bad*: Dependency Hell.
* *Bad*: Integration to other components is not such an easy (field-injection).

==== Mavenizerve Toolbox

Toolbox has started as a showcase for https://github.com/maveniverse/mima[MIMA Resolver], but has a ready-to-use Java DSL for POM generation.
This Java DSL is demonstrated in own Maven plugin / CLI tool, but it can be used as library.

* *Good*: DSL-based
* *Good*: Good integration
* *Good*: Good abstraction of the Maven infrastructure

==== Custom solution based on a template engine

We can start from scratch based on a known template engine that is good integrated with Spring Boot.

* *Good*: We would have the full control.
* *Bad*: We have to implement everything from scratch
* *Bad*: Increase maintenance



=== Links
- https://github.com/sparsick/embedded-maven-shared-toolbox[PoC with shared Mavenizerve Toolbox]
- https://github.com/sparsick/embedded-maven-archetype[PoC with Maven Archetype]
- https://www.baeldung.com/spring-template-engines[List of template engine] that have good integration in Spring
- https://github.com/support-and-care/maven-initializer/issues/3#issuecomment-3324185347[Result of the Kickoff Meeting for Maven initializer]