name-template: "v$RESOLVED_VERSION 🌟"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Fixes"
    labels:
      - "bug"
      - "fix"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "dependencies"
  - title: "⚡ Performance"
    labels:
      - "performance"
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes since last release

  $CHANGES

  _Thanks to all contributors!_
  $CONTRIBUTORS
